**Weather Prediction Using manual Backpropagation**
<br> resource data : https://www.kaggle.com/datasets/ananthr1/weather-prediction

In [ ]:
import pandas as pd
import numpy as np

from google.colab import files
uploaded = files.upload()
cuaca = pd.read_excel('weather.xlsx')
print(cuaca)

Saving weather.xlsx to weather (8).xlsx
      temp_max  temp_min  wind  weather
0         12.8       5.0   4.7        3
1         10.6       2.8   4.5        1
2         11.7       7.2   2.3        1
3         12.2       5.6   4.7        1
4          8.9       2.8   6.1        1
...        ...       ...   ...      ...
1456       4.4       1.7   2.9        1
1457       5.0       1.7   1.3        1
1458       7.2       0.6   2.6        5
1459       5.6      -1.0   3.4        2
1460       5.6      -2.1   3.5        2

[1461 rows x 4 columns]


In [ ]:
data=pd.DataFrame(cuaca, columns=['temp_max', 'temp_min', 'wind', 'weather'])
xAll=cuaca.iloc[:,0:3].values #mengambil variable input
y=cuaca.iloc[:,-1:].values #mengambil variable output

print(xAll)
print(y)

[[12.8  5.   4.7]
 [10.6  2.8  4.5]
 [11.7  7.2  2.3]
 ...
 [ 7.2  0.6  2.6]
 [ 5.6 -1.   3.4]
 [ 5.6 -2.1  3.5]]
[[3]
 [1]
 [1]
 ...
 [5]
 [2]
 [2]]


In [ ]:
xAll = xAll/np.amax(xAll, axis=0) # scaling input data
y = y/5 # scaling output data

In [ ]:
#split data
X = np.split(xAll, [3])[0] # training data
x_predicted = np.split(xAll, [3])[1] # testing data

In [ ]:
y = cuaca.iloc[:,-1].values
y = y/5 # max point is 5

In [ ]:
class neural_network(object):
  def __init__(self):
  #parameters
    self.inputSize = 3
    self.outputSize = 1
    self.hiddenSize = 9

  #weights
    self.W1 = np.random.randn(self.inputSize, self.hiddenSize) # (3x9) weight matrix from input to hidden layer
    self.W2 = np.random.randn(self.hiddenSize, self.outputSize) # (9x1) weight matrix from hidden to output layer

  def forward(self, X):
    #forward propagation through our network
    self.z = np.dot(X, self.W1) # dot product of X (input) and first set of 3x9 weights
    self.z2 = self.sigmoid(self.z) # activation function
    self.z3 = np.dot(self.z2, self.W2) # dot product of hidden layer (z2) and second set of 3x1 weights
    o = self.sigmoid(self.z3) # final activation function
    return o

  def sigmoid(self, s):
    # activation function
    return 1/(1+np.exp(-s))

  def sigmoidPrime(self, s):
    #derivative of sigmoid
    return s * (1 - s)

  def backward(self, X, y, o):
    # backward propagate through the network
    self.o_error = y - o # error in output
    self.o_delta = self.o_error*self.sigmoidPrime(o) # applying derivative of sigmoid to error

    self.z2_error = self.o_delta.dot(self.W2.T) # z2 error: how much our hidden layer weights contributed to output error
    self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2) # applying derivative of sigmoid to z2 error

    self.W1 += X.T.dot(self.z2_delta) # adjusting first set (input --> hidden) weights
    self.W2 += self.z2.T.dot(self.o_delta) # adjusting second set (hidden --> output) weights

  def train(self, X, y):
    o = self.forward(X)
    self.backward(X, y, o)

  def saveWeights(self):
    np.savetxt("w1.txt", self.W1, fmt="%s")
    np.savetxt("w2.txt", self.W2, fmt="%s")

  def predict(self):
    print("Predicted data based on trained weights: ")
    print("Input (scaled): \n" + str(x_predicted))
    print("Output: \n" + str(self.forward(x_predicted)))

In [ ]:
nn = neural_network()
for i in range(200): # trains the nn 200 times
  print("# " + str(i) + "\n")
  print("Input (scaled): \n" + str(X))
  print("Actual Output: \n" + str(y))
  print("Predicted Output: \n" + str(nn.forward(X)))
  print("Loss: \n" + str(np.mean(np.square(y - nn.forward(X))))) # mean squared error
  print("\n")

nn.saveWeights()
nn.predict()

# 0

Input (scaled): 
[[0.35955056 0.27322404 0.49473684]
 [0.29775281 0.15300546 0.47368421]
 [0.32865169 0.39344262 0.24210526]]
Actual Output: 
[0.6 0.2 0.2 ... 1.  0.4 0.4]
Predicted Output: 
[[0.22807963]
 [0.20449909]
 [0.23257767]]
Loss: 
0.06729803068847942


# 1

Input (scaled): 
[[0.35955056 0.27322404 0.49473684]
 [0.29775281 0.15300546 0.47368421]
 [0.32865169 0.39344262 0.24210526]]
Actual Output: 
[0.6 0.2 0.2 ... 1.  0.4 0.4]
Predicted Output: 
[[0.22807963]
 [0.20449909]
 [0.23257767]]
Loss: 
0.06729803068847942


# 2

Input (scaled): 
[[0.35955056 0.27322404 0.49473684]
 [0.29775281 0.15300546 0.47368421]
 [0.32865169 0.39344262 0.24210526]]
Actual Output: 
[0.6 0.2 0.2 ... 1.  0.4 0.4]
Predicted Output: 
[[0.22807963]
 [0.20449909]
 [0.23257767]]
Loss: 
0.06729803068847942


# 3

Input (scaled): 
[[0.35955056 0.27322404 0.49473684]
 [0.29775281 0.15300546 0.47368421]
 [0.32865169 0.39344262 0.24210526]]
Actual Output: 
[0.6 0.2 0.2 ... 1.  0.4 0.4]
Predicted Output: 


In [ ]:
#Hasil Prediksi
hasil=nn.forward(X)
print(X)
print(hasil)

[[0.35955056 0.27322404 0.49473684]
 [0.29775281 0.15300546 0.47368421]
 [0.32865169 0.39344262 0.24210526]]
[[0.22807963]
 [0.20449909]
 [0.23257767]]


In [ ]:
high = input('Input Temperatur Maksimal: ')
low = input('Input Temperatur Minimal: ')
wind = input('Input angin: ')

weather=nn.forward([[float(high),float(low),float(wind)]])
print('Cuaca hari ini adalah :')
print(weather)

Input Temperatur Maksimal: 12
Input Temperatur Minimal: 3
Input angin: 5
Cuaca hari ini adalah :
[[0.69029504]]
